### ISSUE TITLE
Avoid wrapping fields in getters and setters just to be "safe" 

### ISSUE THREAD

**Issue by arnoldosilva** [PeterHdd/gettersetter#1]
Hi! i change this line s = `\n ${type} get ${varLowerName.replace("_", "")} => ${variableName};`; to s = `\n ${type} get ${varLowerName.replace("_", "")} => this.${variableName};`; 

thanks for your VSCODE extension.

**Comment by PeterHdd** [comment]
Thank you, I finally changed it!
