### ISSUE TITLE
extension does not work with constructor

### ISSUE THREAD

**Issue by huzeyfetas** [PeterHdd/gettersetter#8]
![aa](https://user-images.githubusercontent.com/49512381/114469670-46fa4900-9bf6-11eb-8899-f094015ec59f.png)

While it works fine for non-private items, unfortunately it doesn't work for private items. If I delete the underline at the beginning of the items, I can see the getters and setters, but I cannot see them as they are, and I get an error message as it appears at the bottom right.

**Comment by PeterHdd** [comment]
https://user-images.githubusercontent.com/29070108/114615568-84221200-9cae-11eb-98cc-de6394bcb85e.mp4

Are you not getting the above getter/setters as in the video?

**Comment by huzeyfetas** [comment]
I tested it in a few different ways and I think problem is constructor. If I have private or public instance fields and if I did not created a constructor yet, yes I have getters and setters like the video. But if I have already a constructor, private or public instance fields does not matter . It gives the error "Setter and getter already created" in the right below warning.

**Comment by PeterHdd** [comment]
fixed in 4527c1947ddcb7b7de719be5410dfac0a21e6b33 and published, so just update the extension in vscode and it should work normally even if there is a constructor 👍
